Added peopleSubscription API method
crisp-im/php-crisp-api pull request #26
Opened 2020-09-23 13:22 UTC by rankarpan

- Resolves subscription status for people (subscribed or unsubscribed).
- Updates current subscription status for people (subscribed or unsubscribed).

2020-10-23 11:00 UTC, eliottvincent requested changes
Hey thanks for the PR!

There are two small changes to do, I'll be able to merge after 👍

2020-10-23 11:00 UTC, eliottvincent commented on resources/WebsitePeople.php
> +    return $result->decode_response();
Should be updated to `formatResponse` (see our last merge).

2020-10-23 11:00 UTC, eliottvincent commented on resources/WebsitePeople.php
> +    return $result->decode_response()["data"];
Should be updated to `formatResponse` (see our last merge).

2020-11-19 05:07 UTC, rankarpan commented on resources/WebsitePeople.php
> +    return $result->decode_response();
@eliottvincent I have updated to `formatResponse`.

2020-11-19 05:08 UTC, rankarpan commented on resources/WebsitePeople.php
> +    return $result->decode_response()["data"];
@eliottvincent I have updated to `formatResponse`.

2020-11-19 07:54 UTC, merged